apiVersion: v1
kind: Pod
metadata:
  name:  myapache
  labels:
    app: apache
    tier: web-server
spec:
  containers:
    -name: apache
    image: apache
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: "1024Mi"
        memory: "1"   